-- IGProtocol scaffold: VINIT → AFWD → FSPLIT → EVALT → FFUSE → IFIX → CLINK → FSPLIT → EVALF → AREV → ENGAGR → IMSCRIB → FFUSE → TANCH
-- Class: The inter-universal Teichm¨uller theory developed in [IUTchI], [IUTchII], [IUTchIII],\n[IUTchIV] arose from attempts by the author, which began around the summer of\n2000, to overcome certain technical obstructions in the scheme-theoretic Hodge-\nArakelov theory of [HASurI], [HASurII] to applying this theory to diophantine geom-\netry [cf. the discussion of [HASurI], §1.5.1; [HASurII], Remark 3.7; [IUTchI], Remark\n4.3.1]. Thus, we begin our overview of inter-universal Teichm¨uller theory with a brief\nreview of the essential content of those aspects of scheme-theoretic Hodge-Arakelov\ntheory that are relevant to the development of inter-universal Teichm¨uller theory.\nLet l be a prime number. Then we recall that the module E[l] of l-torsion points\nof a Tate curve E def\n= Gm/qZ [over, say, a p-adic field or the complex field C], whose\nq-parameter we denote by q, fits into a natural exact sequence\n0 −→ μl −→ E[l] −→ Z/lZ −→ 0.\nThat is to say, one has canonical objects as follows:\na “multiplicative subspace” μl ⊆ E[l] and “generators” ±1 ∈ Z/lZ.\nIn the following discussion, we fix an elliptic curve E over a number field F\nand a prime number l ≥ 5. For convenience, we shall use the notation\nl def\n= l−1\n2 .\nAlso, we suppose that E has stable reduction at all nonarchimedean primes of F . Then,\nin general, the module E[l] [i.e., more precisely, the finite ´etale group scheme over F ] of\nl-torsion points of E does not admit\na “global multiplicative subspace” or “global canonical generators”\n— i.e., a rank one submodule M ⊆ E[l] or a pair of generators of the quotient E[l]/M\nthat coincide with the above canonical multiplicative subspace and generators at all\nnonarchimedean primes of F where E has bad multiplicative reduction. Nevertheless,\nlet us\nsuppose that such global objects do in fact exist\nAlso, let us write\nK def\n= F (E[l])\nfor the extension field of F generated by the fields of definition of the l-torsion points\nof E, V(K) for the set of [archimedean and nonarchimedean] valuations of K, and\nA Panoramic Overview of Inter-universal Teichm¨uller Theory 3\nV(K)bad ⊆ V(K) for the set of nonarchimedean valuations where E has bad multiplica-\ntive reduction. For v ∈ V(K), we shall write Kv for the completion of K at v, Ov ⊆ Kv\nfor the subset of elements f ∈ Kv such that |f |v ≤ 1, and mv ⊆ Ov for the subset of\nelements f ∈ Kv such that |f |v < 1. Let N ⊆ E[l] be a rank one submodule such that\nthe natural morphism of finite group schemes over F\nM × N ∼\n→ E[l]\nis an isomorphism. Then the Fundamental Theorem of Hodge-Arakelov Theory may be\nformulated as follows [cf. [HASurI], §1; [HASurII], §1, §3; the explicit series representa-\ntion of the theta function on a Tate curve given in [EtTh], Proposition 1.4]
-- Fingerprint: sig=(6,4,3,1)
--   self_ref=False | frobenius_order=3
--   dialetheia_complete=True | period=14
-- Expected tier: O₁
-- FSPLIT/FFUSE pairs: [(2, 4), (7, 12)]

import Imscribing.IGMorphism
import Imscribing.IGFunctor

namespace Imscribing
open Primitives Frobenius IGProtocol
open Dimensionality Topology Relational Polarity Grammar
     Fidelity KineticChar Granularity Criticality Protection Stoichiometry Chirality

-- ── Token → IG field mapping ──────────────────────────────────────────────
--   [0] VINIT     dim    := 𐑼               𐑼 → 𐑾  | initial object — ground of distinction
--   [1] AFWD      rel    := 𐑾               𐑼 → 𐑚  | forward morphism — bidirectional arrow
--   [2] FSPLIT    gran   := 𐑚               𐑚 → 𐑚  | split δ — range decomposition
--   [3] EVALT     crit   := ⊙               𐑚 → 𐑙  | evaluate-true — criticality gate open
--   [4] FFUSE     stoi   := 𐑙               𐑙 → 𐑭  | fuse μ — assembly mode
--   [5] IFIX      prot   := 𐑭               𐑙 → 𐑱  | irreversible fixation — winding number
--   [6] CLINK     fid    := 𐑱               𐑭 → 𐑚  | composition — regime coherence
--   [7] FSPLIT    gran   := 𐑚               𐑚 → 𐑚  | split δ — range decomposition
--   [8] EVALF     chir   := 𐑖               𐑚 → 𐑙  | evaluate-false — chirality check
--   [9] AREV      pol    := 𐑗               𐑚 → 𐑙  | reverse morphism — parity flip
--   [10] ENGAGR    stoi   := 𐑳               𐑚 → 𐑙  | engage paradox — B-state, both arms
--   [11] IMSCRIB   gram   := 𐑠               𐑚 → 𐑙  | identity — self-imscription
--   [12] FFUSE     stoi   := 𐑙               𐑙 → 𐑡  | fuse μ — assembly mode
--   [13] TANCH     top    := 𐑡               𐑙 → 𐑼  | terminal object — connectivity boundary

-- ── Stage Imscriptions (per-node cumulative) ────────────────
private def the_inter_universal_teichm_uller_theory_909207_s0 : Imscription :=
  { dim := array, top := judge, rel := ado, pol := church, fid := age, kin := yea, gran := bib, gram := vow, crit := woe, chir := fee, stoi := hung, prot := awe }
private def the_inter_universal_teichm_uller_theory_909207_s1 : Imscription :=
  { dim := array, top := judge, rel := ian, pol := church, fid := age, kin := yea, gran := bib, gram := vow, crit := woe, chir := fee, stoi := hung, prot := awe }
private def the_inter_universal_teichm_uller_theory_909207_s2 : Imscription :=
  { dim := array, top := judge, rel := ian, pol := church, fid := age, kin := yea, gran := thigh, gram := vow, crit := woe, chir := fee, stoi := hung, prot := awe }
private def the_inter_universal_teichm_uller_theory_909207_s3 : Imscription :=
  { dim := array, top := judge, rel := ian, pol := church, fid := age, kin := yea, gran := thigh, gram := vow, crit := monad, chir := fee, stoi := hung, prot := awe }
private def the_inter_universal_teichm_uller_theory_909207_s4 : Imscription :=
  { dim := array, top := judge, rel := ian, pol := church, fid := age, kin := yea, gran := thigh, gram := vow, crit := monad, chir := fee, stoi := hung, prot := awe }
private def the_inter_universal_teichm_uller_theory_909207_s5 : Imscription :=
  { dim := array, top := judge, rel := ian, pol := church, fid := age, kin := yea, gran := thigh, gram := vow, crit := monad, chir := fee, stoi := hung, prot := ah }
private def the_inter_universal_teichm_uller_theory_909207_s6 : Imscription :=
  { dim := array, top := judge, rel := ian, pol := church, fid := age, kin := yea, gran := thigh, gram := vow, crit := monad, chir := fee, stoi := hung, prot := ah }
private def the_inter_universal_teichm_uller_theory_909207_s7 : Imscription :=
  { dim := array, top := judge, rel := ian, pol := church, fid := age, kin := yea, gran := thigh, gram := vow, crit := monad, chir := fee, stoi := hung, prot := ah }
private def the_inter_universal_teichm_uller_theory_909207_s8 : Imscription :=
  { dim := array, top := judge, rel := ian, pol := church, fid := age, kin := yea, gran := thigh, gram := vow, crit := monad, chir := sure, stoi := hung, prot := ah }
private def the_inter_universal_teichm_uller_theory_909207_s9 : Imscription :=
  { dim := array, top := judge, rel := ian, pol := church, fid := age, kin := yea, gran := thigh, gram := vow, crit := monad, chir := sure, stoi := hung, prot := ah }
private def the_inter_universal_teichm_uller_theory_909207_s10 : Imscription :=
  { dim := array, top := judge, rel := ian, pol := church, fid := age, kin := yea, gran := thigh, gram := vow, crit := monad, chir := sure, stoi := up, prot := ah }
private def the_inter_universal_teichm_uller_theory_909207_s11 : Imscription :=
  { dim := array, top := judge, rel := ian, pol := church, fid := age, kin := yea, gran := thigh, gram := measure, crit := monad, chir := sure, stoi := up, prot := ah }
private def the_inter_universal_teichm_uller_theory_909207_s12 : Imscription :=
  { dim := array, top := judge, rel := ian, pol := church, fid := age, kin := yea, gran := thigh, gram := measure, crit := monad, chir := sure, stoi := hung, prot := ah }
private def the_inter_universal_teichm_uller_theory_909207_s13 : Imscription :=
  { dim := array, top := judge, rel := ian, pol := church, fid := age, kin := yea, gran := thigh, gram := measure, crit := monad, chir := sure, stoi := hung, prot := ah }

-- ── Label Imscriptions (per-node delta) ─────────────────────
private def the_inter_universal_teichm_uller_theory_909207_l0 : Imscription :=
  { dim := array, top := judge, rel := ado, pol := church, fid := age, kin := yea, gran := bib, gram := vow, crit := woe, chir := fee, stoi := hung, prot := awe }
private def the_inter_universal_teichm_uller_theory_909207_l1 : Imscription :=
  { dim := dead, top := judge, rel := ian, pol := church, fid := age, kin := yea, gran := bib, gram := vow, crit := woe, chir := fee, stoi := hung, prot := awe }
private def the_inter_universal_teichm_uller_theory_909207_l2 : Imscription :=
  { dim := dead, top := judge, rel := ado, pol := church, fid := age, kin := yea, gran := thigh, gram := vow, crit := woe, chir := fee, stoi := hung, prot := awe }
private def the_inter_universal_teichm_uller_theory_909207_l3 : Imscription :=
  { dim := dead, top := judge, rel := ado, pol := church, fid := age, kin := yea, gran := bib, gram := vow, crit := monad, chir := fee, stoi := hung, prot := awe }
private def the_inter_universal_teichm_uller_theory_909207_l4 : Imscription :=
  { dim := dead, top := judge, rel := ado, pol := church, fid := age, kin := yea, gran := bib, gram := vow, crit := woe, chir := fee, stoi := hung, prot := awe }
private def the_inter_universal_teichm_uller_theory_909207_l5 : Imscription :=
  { dim := dead, top := judge, rel := ado, pol := church, fid := age, kin := yea, gran := bib, gram := vow, crit := woe, chir := fee, stoi := hung, prot := ah }
private def the_inter_universal_teichm_uller_theory_909207_l6 : Imscription :=
  { dim := dead, top := judge, rel := ado, pol := church, fid := age, kin := yea, gran := bib, gram := vow, crit := woe, chir := fee, stoi := hung, prot := awe }
private def the_inter_universal_teichm_uller_theory_909207_l7 : Imscription :=
  { dim := dead, top := judge, rel := ado, pol := church, fid := age, kin := yea, gran := thigh, gram := vow, crit := woe, chir := fee, stoi := hung, prot := awe }
private def the_inter_universal_teichm_uller_theory_909207_l8 : Imscription :=
  { dim := dead, top := judge, rel := ado, pol := church, fid := age, kin := yea, gran := bib, gram := vow, crit := woe, chir := sure, stoi := hung, prot := awe }
private def the_inter_universal_teichm_uller_theory_909207_l9 : Imscription :=
  { dim := dead, top := judge, rel := ado, pol := church, fid := age, kin := yea, gran := bib, gram := vow, crit := woe, chir := fee, stoi := hung, prot := awe }
private def the_inter_universal_teichm_uller_theory_909207_l10 : Imscription :=
  { dim := dead, top := judge, rel := ado, pol := church, fid := age, kin := yea, gran := bib, gram := vow, crit := woe, chir := fee, stoi := up, prot := awe }
private def the_inter_universal_teichm_uller_theory_909207_l11 : Imscription :=
  { dim := dead, top := judge, rel := ado, pol := church, fid := age, kin := yea, gran := bib, gram := measure, crit := woe, chir := fee, stoi := hung, prot := awe }
private def the_inter_universal_teichm_uller_theory_909207_l12 : Imscription :=
  { dim := dead, top := judge, rel := ado, pol := church, fid := age, kin := yea, gran := bib, gram := vow, crit := woe, chir := fee, stoi := hung, prot := awe }
private def the_inter_universal_teichm_uller_theory_909207_l13 : Imscription :=
  { dim := dead, top := judge, rel := ado, pol := church, fid := age, kin := yea, gran := bib, gram := vow, crit := woe, chir := fee, stoi := hung, prot := awe }

-- ── Main IGProtocol term ────────────────────────────────────
noncomputable def the_inter_universal_teichm_uller_theory_909207_protocol : IGProtocol the_inter_universal_teichm_uller_theory_909207_s0 the_inter_universal_teichm_uller_theory_909207_s13 :=
  .withGram Grammar.measure <|
  -- Dual-Link self-pairing: .prod arms fuse via tensorProduct the_inter_universal_teichm_uller_theory_909207_s4 the_inter_universal_teichm_uller_theory_909207_s4 = the_inter_universal_teichm_uller_theory_909207_s4 (idempotent)
  (.seq (.arrow the_inter_universal_teichm_uller_theory_909207_l0 the_inter_universal_teichm_uller_theory_909207_s0 the_inter_universal_teichm_uller_theory_909207_s1) (.seq (.arrow the_inter_universal_teichm_uller_theory_909207_l1 the_inter_universal_teichm_uller_theory_909207_s1 the_inter_universal_teichm_uller_theory_909207_s2) (.seq (.prod (.arrow the_inter_universal_teichm_uller_theory_909207_l2 the_inter_universal_teichm_uller_theory_909207_s2 the_inter_universal_teichm_uller_theory_909207_s4) (.arrow the_inter_universal_teichm_uller_theory_909207_l2 the_inter_universal_teichm_uller_theory_909207_s2 the_inter_universal_teichm_uller_theory_909207_s4)) (.seq (.arrow the_inter_universal_teichm_uller_theory_909207_l4 the_inter_universal_teichm_uller_theory_909207_s4 the_inter_universal_teichm_uller_theory_909207_s4) (.seq (.arrow the_inter_universal_teichm_uller_theory_909207_l4 the_inter_universal_teichm_uller_theory_909207_s4 the_inter_universal_teichm_uller_theory_909207_s5) (.seq (.arrow the_inter_universal_teichm_uller_theory_909207_l5 the_inter_universal_teichm_uller_theory_909207_s5 the_inter_universal_teichm_uller_theory_909207_s6) (.seq (.arrow the_inter_universal_teichm_uller_theory_909207_l6 the_inter_universal_teichm_uller_theory_909207_s6 the_inter_universal_teichm_uller_theory_909207_s7) (.seq (.arrow the_inter_universal_teichm_uller_theory_909207_l7 the_inter_universal_teichm_uller_theory_909207_s7 the_inter_universal_teichm_uller_theory_909207_s8) (.seq (.arrow the_inter_universal_teichm_uller_theory_909207_l8 the_inter_universal_teichm_uller_theory_909207_s8 the_inter_universal_teichm_uller_theory_909207_s9) (.seq (.arrow the_inter_universal_teichm_uller_theory_909207_l9 the_inter_universal_teichm_uller_theory_909207_s9 the_inter_universal_teichm_uller_theory_909207_s10) (.seq (.arrow the_inter_universal_teichm_uller_theory_909207_l10 the_inter_universal_teichm_uller_theory_909207_s10 the_inter_universal_teichm_uller_theory_909207_s11) (.seq (.arrow the_inter_universal_teichm_uller_theory_909207_l11 the_inter_universal_teichm_uller_theory_909207_s11 the_inter_universal_teichm_uller_theory_909207_s12) (.arrow the_inter_universal_teichm_uller_theory_909207_l12 the_inter_universal_teichm_uller_theory_909207_s12 the_inter_universal_teichm_uller_theory_909207_s13)))))))))))))

-- ── Evaluation arm sub-defs ───────────────────────────────────

-- truth arm
noncomputable def the_inter_universal_teichm_uller_theory_909207_true_arm : IGProtocol the_inter_universal_teichm_uller_theory_909207_s0 the_inter_universal_teichm_uller_theory_909207_s13 :=
  (the_inter_universal_teichm_uller_theory_909207_protocol).restrictToEVALT

-- false arm
noncomputable def the_inter_universal_teichm_uller_theory_909207_false_arm : IGProtocol the_inter_universal_teichm_uller_theory_909207_s0 the_inter_universal_teichm_uller_theory_909207_s13 :=
  (the_inter_universal_teichm_uller_theory_909207_protocol).restrictToEVALF

-- ── Verification theorems ─────────────────────────────────────

-- Tier: apply the Grammar to the object (self-application). assess_tier verdict on the imscribed tuple: .O₁.
def the_inter_universal_teichm_uller_theory_909207_tier : OuroboricityTier := TierFunctor.obj the_inter_universal_teichm_uller_theory_909207_s0
#eval the_inter_universal_teichm_uller_theory_909207_tier  -- the Grammar's own verdict on its tier
