-- IGProtocol scaffold: VINIT → AFWD → FSPLIT → EVALT → AREV → EVALF → FFUSE → CLINK → IMSCRIB → ENGAGR → AFWD → CLINK → FSPLIT → EVALT → AREV → FFUSE → IMSCRIB → IFIX → TANCH
-- Class: the explicit generators of the conductor-36 ray class field of Q(sqrt13) recovered from the d=12 fiducial become a concrete instance of Hilbert's twelfth problem for a real quadratic field, an abelian extension generated by SIC coordinates rather than by transcendental special values
-- Fingerprint: sig=(10,4,4,1)
--   self_ref=False | frobenius_order=3
--   dialetheia_complete=True | period=19
-- Expected tier: O₁
-- FSPLIT/FFUSE pairs: [(2, 6), (12, 15)]

import Imscribing.IGMorphism
import Imscribing.IGFunctor

namespace Imscribing
open Primitives Frobenius IGProtocol
open Dimensionality Topology Relational Polarity Grammar
     Fidelity KineticChar Granularity Criticality Protection Stoichiometry Chirality

-- ── Token → IG field mapping ──────────────────────────────────────────────
--   [0] VINIT     dim    := 𐑼               𐑼 → 𐑾  | initial object — ground of distinction
--   [1] AFWD      rel    := 𐑾               𐑼 → 𐑚  | forward morphism — bidirectional arrow
--   [2] FSPLIT    gran   := 𐑚               𐑚 → 𐑚  | split δ — range decomposition
--   [3] EVALT     crit   := ⊙               𐑚 → 𐑙  | evaluate-true — criticality gate open
--   [4] AREV      pol    := 𐑗               𐑚 → 𐑙  | reverse morphism — parity flip
--   [5] EVALF     chir   := 𐑖               𐑚 → 𐑙  | evaluate-false — chirality check
--   [6] FFUSE     stoi   := 𐑙               𐑙 → 𐑱  | fuse μ — assembly mode
--   [7] CLINK     fid    := 𐑱               𐑙 → 𐑠  | composition — regime coherence
--   [8] IMSCRIB   gram   := 𐑠               𐑱 → 𐑳  | identity — self-imscription
--   [9] ENGAGR    stoi   := 𐑳               𐑠 → 𐑾  | engage paradox — B-state, both arms
--   [10] AFWD      rel    := 𐑾               𐑳 → 𐑱  | forward morphism — bidirectional arrow
--   [11] CLINK     fid    := 𐑱               𐑾 → 𐑚  | composition — regime coherence
--   [12] FSPLIT    gran   := 𐑚               𐑚 → 𐑚  | split δ — range decomposition
--   [13] EVALT     crit   := ⊙               𐑚 → 𐑙  | evaluate-true — criticality gate open
--   [14] AREV      pol    := 𐑗               𐑚 → 𐑙  | reverse morphism — parity flip
--   [15] FFUSE     stoi   := 𐑙               𐑙 → 𐑠  | fuse μ — assembly mode
--   [16] IMSCRIB   gram   := 𐑠               𐑙 → 𐑭  | identity — self-imscription
--   [17] IFIX      prot   := 𐑭               𐑠 → 𐑡  | irreversible fixation — winding number
--   [18] TANCH     top    := 𐑡               𐑭 → 𐑼  | terminal object — connectivity boundary

-- ── Stage Imscriptions (per-node cumulative) ────────────────
private def the_explicit_generators_of_the_576561_s0 : Imscription :=
  { dim := array, top := judge, rel := ado, pol := church, fid := age, kin := yea, gran := bib, gram := vow, crit := woe, chir := fee, stoi := hung, prot := awe }
private def the_explicit_generators_of_the_576561_s1 : Imscription :=
  { dim := array, top := judge, rel := ian, pol := church, fid := age, kin := yea, gran := bib, gram := vow, crit := woe, chir := fee, stoi := hung, prot := awe }
private def the_explicit_generators_of_the_576561_s2 : Imscription :=
  { dim := array, top := judge, rel := ian, pol := church, fid := age, kin := yea, gran := thigh, gram := vow, crit := woe, chir := fee, stoi := hung, prot := awe }
private def the_explicit_generators_of_the_576561_s3 : Imscription :=
  { dim := array, top := judge, rel := ian, pol := church, fid := age, kin := yea, gran := thigh, gram := vow, crit := monad, chir := fee, stoi := hung, prot := awe }
private def the_explicit_generators_of_the_576561_s4 : Imscription :=
  { dim := array, top := judge, rel := ian, pol := church, fid := age, kin := yea, gran := thigh, gram := vow, crit := monad, chir := fee, stoi := hung, prot := awe }
private def the_explicit_generators_of_the_576561_s5 : Imscription :=
  { dim := array, top := judge, rel := ian, pol := church, fid := age, kin := yea, gran := thigh, gram := vow, crit := monad, chir := sure, stoi := hung, prot := awe }
private def the_explicit_generators_of_the_576561_s6 : Imscription :=
  { dim := array, top := judge, rel := ian, pol := church, fid := age, kin := yea, gran := thigh, gram := vow, crit := monad, chir := sure, stoi := hung, prot := awe }
private def the_explicit_generators_of_the_576561_s7 : Imscription :=
  { dim := array, top := judge, rel := ian, pol := church, fid := age, kin := yea, gran := thigh, gram := vow, crit := monad, chir := sure, stoi := hung, prot := awe }
private def the_explicit_generators_of_the_576561_s8 : Imscription :=
  { dim := array, top := judge, rel := ian, pol := church, fid := age, kin := yea, gran := thigh, gram := measure, crit := monad, chir := sure, stoi := hung, prot := awe }
private def the_explicit_generators_of_the_576561_s9 : Imscription :=
  { dim := array, top := judge, rel := ian, pol := church, fid := age, kin := yea, gran := thigh, gram := measure, crit := monad, chir := sure, stoi := up, prot := awe }
private def the_explicit_generators_of_the_576561_s10 : Imscription :=
  { dim := array, top := judge, rel := ian, pol := church, fid := age, kin := yea, gran := thigh, gram := measure, crit := monad, chir := sure, stoi := up, prot := awe }
private def the_explicit_generators_of_the_576561_s11 : Imscription :=
  { dim := array, top := judge, rel := ian, pol := church, fid := age, kin := yea, gran := thigh, gram := measure, crit := monad, chir := sure, stoi := up, prot := awe }
private def the_explicit_generators_of_the_576561_s12 : Imscription :=
  { dim := array, top := judge, rel := ian, pol := church, fid := age, kin := yea, gran := thigh, gram := measure, crit := monad, chir := sure, stoi := up, prot := awe }
private def the_explicit_generators_of_the_576561_s13 : Imscription :=
  { dim := array, top := judge, rel := ian, pol := church, fid := age, kin := yea, gran := thigh, gram := measure, crit := monad, chir := sure, stoi := up, prot := awe }
private def the_explicit_generators_of_the_576561_s14 : Imscription :=
  { dim := array, top := judge, rel := ian, pol := church, fid := age, kin := yea, gran := thigh, gram := measure, crit := monad, chir := sure, stoi := up, prot := awe }
private def the_explicit_generators_of_the_576561_s15 : Imscription :=
  { dim := array, top := judge, rel := ian, pol := church, fid := age, kin := yea, gran := thigh, gram := measure, crit := monad, chir := sure, stoi := hung, prot := awe }
private def the_explicit_generators_of_the_576561_s16 : Imscription :=
  { dim := array, top := judge, rel := ian, pol := church, fid := age, kin := yea, gran := thigh, gram := measure, crit := monad, chir := sure, stoi := hung, prot := awe }
private def the_explicit_generators_of_the_576561_s17 : Imscription :=
  { dim := array, top := judge, rel := ian, pol := church, fid := age, kin := yea, gran := thigh, gram := measure, crit := monad, chir := sure, stoi := hung, prot := ah }
private def the_explicit_generators_of_the_576561_s18 : Imscription :=
  { dim := array, top := judge, rel := ian, pol := church, fid := age, kin := yea, gran := thigh, gram := measure, crit := monad, chir := sure, stoi := hung, prot := ah }

-- ── Label Imscriptions (per-node delta) ─────────────────────
private def the_explicit_generators_of_the_576561_l0 : Imscription :=
  { dim := array, top := judge, rel := ado, pol := church, fid := age, kin := yea, gran := bib, gram := vow, crit := woe, chir := fee, stoi := hung, prot := awe }
private def the_explicit_generators_of_the_576561_l1 : Imscription :=
  { dim := dead, top := judge, rel := ian, pol := church, fid := age, kin := yea, gran := bib, gram := vow, crit := woe, chir := fee, stoi := hung, prot := awe }
private def the_explicit_generators_of_the_576561_l2 : Imscription :=
  { dim := dead, top := judge, rel := ado, pol := church, fid := age, kin := yea, gran := thigh, gram := vow, crit := woe, chir := fee, stoi := hung, prot := awe }
private def the_explicit_generators_of_the_576561_l3 : Imscription :=
  { dim := dead, top := judge, rel := ado, pol := church, fid := age, kin := yea, gran := bib, gram := vow, crit := monad, chir := fee, stoi := hung, prot := awe }
private def the_explicit_generators_of_the_576561_l4 : Imscription :=
  { dim := dead, top := judge, rel := ado, pol := church, fid := age, kin := yea, gran := bib, gram := vow, crit := woe, chir := fee, stoi := hung, prot := awe }
private def the_explicit_generators_of_the_576561_l5 : Imscription :=
  { dim := dead, top := judge, rel := ado, pol := church, fid := age, kin := yea, gran := bib, gram := vow, crit := woe, chir := sure, stoi := hung, prot := awe }
private def the_explicit_generators_of_the_576561_l6 : Imscription :=
  { dim := dead, top := judge, rel := ado, pol := church, fid := age, kin := yea, gran := bib, gram := vow, crit := woe, chir := fee, stoi := hung, prot := awe }
private def the_explicit_generators_of_the_576561_l7 : Imscription :=
  { dim := dead, top := judge, rel := ado, pol := church, fid := age, kin := yea, gran := bib, gram := vow, crit := woe, chir := fee, stoi := hung, prot := awe }
private def the_explicit_generators_of_the_576561_l8 : Imscription :=
  { dim := dead, top := judge, rel := ado, pol := church, fid := age, kin := yea, gran := bib, gram := measure, crit := woe, chir := fee, stoi := hung, prot := awe }
private def the_explicit_generators_of_the_576561_l9 : Imscription :=
  { dim := dead, top := judge, rel := ado, pol := church, fid := age, kin := yea, gran := bib, gram := vow, crit := woe, chir := fee, stoi := up, prot := awe }
private def the_explicit_generators_of_the_576561_l10 : Imscription :=
  { dim := dead, top := judge, rel := ian, pol := church, fid := age, kin := yea, gran := bib, gram := vow, crit := woe, chir := fee, stoi := hung, prot := awe }
private def the_explicit_generators_of_the_576561_l11 : Imscription :=
  { dim := dead, top := judge, rel := ado, pol := church, fid := age, kin := yea, gran := bib, gram := vow, crit := woe, chir := fee, stoi := hung, prot := awe }
private def the_explicit_generators_of_the_576561_l12 : Imscription :=
  { dim := dead, top := judge, rel := ado, pol := church, fid := age, kin := yea, gran := thigh, gram := vow, crit := woe, chir := fee, stoi := hung, prot := awe }
private def the_explicit_generators_of_the_576561_l13 : Imscription :=
  { dim := dead, top := judge, rel := ado, pol := church, fid := age, kin := yea, gran := bib, gram := vow, crit := monad, chir := fee, stoi := hung, prot := awe }
private def the_explicit_generators_of_the_576561_l14 : Imscription :=
  { dim := dead, top := judge, rel := ado, pol := church, fid := age, kin := yea, gran := bib, gram := vow, crit := woe, chir := fee, stoi := hung, prot := awe }
private def the_explicit_generators_of_the_576561_l15 : Imscription :=
  { dim := dead, top := judge, rel := ado, pol := church, fid := age, kin := yea, gran := bib, gram := vow, crit := woe, chir := fee, stoi := hung, prot := awe }
private def the_explicit_generators_of_the_576561_l16 : Imscription :=
  { dim := dead, top := judge, rel := ado, pol := church, fid := age, kin := yea, gran := bib, gram := measure, crit := woe, chir := fee, stoi := hung, prot := awe }
private def the_explicit_generators_of_the_576561_l17 : Imscription :=
  { dim := dead, top := judge, rel := ado, pol := church, fid := age, kin := yea, gran := bib, gram := vow, crit := woe, chir := fee, stoi := hung, prot := ah }
private def the_explicit_generators_of_the_576561_l18 : Imscription :=
  { dim := dead, top := judge, rel := ado, pol := church, fid := age, kin := yea, gran := bib, gram := vow, crit := woe, chir := fee, stoi := hung, prot := awe }

-- ── Main IGProtocol term ────────────────────────────────────
noncomputable def the_explicit_generators_of_the_576561_protocol : IGProtocol the_explicit_generators_of_the_576561_s0 the_explicit_generators_of_the_576561_s18 :=
  .withGram Grammar.measure <|
  -- Dual-Link self-pairing: .prod arms fuse via tensorProduct the_explicit_generators_of_the_576561_s6 the_explicit_generators_of_the_576561_s6 = the_explicit_generators_of_the_576561_s6 (idempotent)
  (.seq (.arrow the_explicit_generators_of_the_576561_l0 the_explicit_generators_of_the_576561_s0 the_explicit_generators_of_the_576561_s1) (.seq (.arrow the_explicit_generators_of_the_576561_l1 the_explicit_generators_of_the_576561_s1 the_explicit_generators_of_the_576561_s2) (.seq (.prod (.arrow the_explicit_generators_of_the_576561_l2 the_explicit_generators_of_the_576561_s2 the_explicit_generators_of_the_576561_s6) (.arrow the_explicit_generators_of_the_576561_l2 the_explicit_generators_of_the_576561_s2 the_explicit_generators_of_the_576561_s6)) (.seq (.arrow the_explicit_generators_of_the_576561_l6 the_explicit_generators_of_the_576561_s6 the_explicit_generators_of_the_576561_s6) (.seq (.arrow the_explicit_generators_of_the_576561_l6 the_explicit_generators_of_the_576561_s6 the_explicit_generators_of_the_576561_s7) (.seq (.arrow the_explicit_generators_of_the_576561_l7 the_explicit_generators_of_the_576561_s7 the_explicit_generators_of_the_576561_s8) (.seq (.arrow the_explicit_generators_of_the_576561_l8 the_explicit_generators_of_the_576561_s8 the_explicit_generators_of_the_576561_s9) (.seq (.arrow the_explicit_generators_of_the_576561_l9 the_explicit_generators_of_the_576561_s9 the_explicit_generators_of_the_576561_s10) (.seq (.arrow the_explicit_generators_of_the_576561_l10 the_explicit_generators_of_the_576561_s10 the_explicit_generators_of_the_576561_s11) (.seq (.arrow the_explicit_generators_of_the_576561_l11 the_explicit_generators_of_the_576561_s11 the_explicit_generators_of_the_576561_s12) (.seq (.arrow the_explicit_generators_of_the_576561_l12 the_explicit_generators_of_the_576561_s12 the_explicit_generators_of_the_576561_s13) (.seq (.arrow the_explicit_generators_of_the_576561_l13 the_explicit_generators_of_the_576561_s13 the_explicit_generators_of_the_576561_s14) (.seq (.arrow the_explicit_generators_of_the_576561_l14 the_explicit_generators_of_the_576561_s14 the_explicit_generators_of_the_576561_s15) (.seq (.arrow the_explicit_generators_of_the_576561_l15 the_explicit_generators_of_the_576561_s15 the_explicit_generators_of_the_576561_s16) (.seq (.arrow the_explicit_generators_of_the_576561_l16 the_explicit_generators_of_the_576561_s16 the_explicit_generators_of_the_576561_s17) (.arrow the_explicit_generators_of_the_576561_l17 the_explicit_generators_of_the_576561_s17 the_explicit_generators_of_the_576561_s18))))))))))))))))

-- ── Evaluation arm sub-defs ───────────────────────────────────

-- truth arm
noncomputable def the_explicit_generators_of_the_576561_true_arm : IGProtocol the_explicit_generators_of_the_576561_s0 the_explicit_generators_of_the_576561_s18 :=
  (the_explicit_generators_of_the_576561_protocol).restrictToEVALT

-- false arm
noncomputable def the_explicit_generators_of_the_576561_false_arm : IGProtocol the_explicit_generators_of_the_576561_s0 the_explicit_generators_of_the_576561_s18 :=
  (the_explicit_generators_of_the_576561_protocol).restrictToEVALF

-- ── Verification theorems ─────────────────────────────────────

-- Tier: apply the Grammar to the object (self-application). assess_tier verdict on the imscribed tuple: .O₁.
def the_explicit_generators_of_the_576561_tier : OuroboricityTier := TierFunctor.obj the_explicit_generators_of_the_576561_s0
#eval the_explicit_generators_of_the_576561_tier  -- the Grammar's own verdict on its tier
