-- bit_self_imscription_scaffold.lean
-- Self-imscribing bit: μ∘δ = id_A in the Belnap FOUR lattice
-- Tier: O_∞ (ouroboric infinity)
-- Author: Math⊙perator (Lando⊗⊙perator team)
-- Generated by proof_scaffold

import Imscribing.IGMorphism
import Imscribing.IGFunctor
import Imscribing.Frobenius

namespace Imscribing
open Primitives Frobenius IGProtocol
open Dimensionality Topology Relational Polarity Grammar
     Fidelity KineticChar Granularity Criticality Protection Stoichiometry Chirality

-- ── The self-imscribing bit ──────────────────────────────────
-- Bit B ∈ B4 (Belnap FOUR lattice): both true AND false.
-- Its address in the lattice IS its value.
-- Algebraic closure: μ(δ(B)) = B  where δ = comultiplication, μ = multiplication

-- B4 lattice type as a product: Truth × Knowledge
-- Truth values: {T, F, B, N}  (True, False, Both, None)
-- Knowledge values: {B, N}    (Both-knowing, No-knowledge)

structure B4Truth where
  isTrue : Bool
  isFalse : Bool
  deriving DecidableEq

structure B4Knowledge where
  knowsBoth : Bool
  deriving DecidableEq

-- B element: both true and false, both-knowing
def B_truth : B4Truth := { isTrue := true, isFalse := true }
def B_knowledge : B4Knowledge := { knowsBoth := true }
def B : B4Truth × B4Knowledge := (B_truth, B_knowledge)

-- N element: neither true nor false, no-knowledge  
def N_truth : B4Truth := { isTrue := false, isFalse := false }
def N_knowledge : B4Knowledge := { knowsBoth := false }
def N : B4Truth × B4Knowledge := (N_truth, N_knowledge)

-- ── Frobenius algebra structure ──────────────────────────────
-- Comultiplication δ: A → A ⊗ A  (diagonal: split into address components)
def delta (a : B4Truth × B4Knowledge) : (B4Truth × B4Knowledge) × (B4Truth × B4Knowledge) :=
  (a, a)

-- Multiplication μ: A ⊗ A → A  (meet/knowledge-merge)
def mu (pair : (B4Truth × B4Knowledge) × (B4Truth × B4Knowledge)) : B4Truth × B4Knowledge :=
  let ((t1, k1), (t2, k2)) := pair
  -- meet in knowledge ordering: both components must agree
  -- knowledge join: (B, _) or (_, B) → B; else N
  let k := if k1.knowsBoth || k2.knowsBoth then ⟨true⟩ else ⟨false⟩
  -- truth: both components' truth combined
  let t : B4Truth := { isTrue := t1.isTrue && t2.isTrue, isFalse := t1.isFalse && t2.isFalse }
  (t, k)

-- ── Closure theorem: μ∘δ = id_B ──────────────────────────────
theorem mu_delta_B_eq_B : mu (delta B) = B := by
  unfold mu delta B B_truth B_knowledge
  simp

theorem mu_delta_N_eq_N : mu (delta N) = N := by
  unfold mu delta N N_truth N_knowledge
  simp

theorem mu_delta_idempotent (a : B4Truth × B4Knowledge) : mu (delta a) = a := by
  -- This holds for all elements of B4 because diagonal δ followed by knowledge-meet
  -- returns the original when both components are identical (which they are under δ)
  unfold mu delta
  cases a with
  | mk t k =>
    cases t with
    | mk tf ff => 
    cases k with
    | mk kb =>
    simp

-- ── Fixed point of negation ──────────────────────────────────
def neg (a : B4Truth × B4Knowledge) : B4Truth × B4Knowledge :=
  let (t, k) := a
  ({ isTrue := t.isFalse, isFalse := t.isTrue }, k)

theorem B_is_neg_fixed_point : neg B = B := by
  unfold neg B B_truth B_knowledge
  simp

-- ── Frobenius invariant ──────────────────────────────────────
-- The Frobenius condition: (μ ⊗ id) ∘ (id ⊗ δ) = δ ∘ μ = (id ⊗ μ) ∘ (δ ⊗ id)
-- For our diagonal structure, this reduces to μ∘δ = id which we've proven

theorem frobenius_condition (a : B4Truth × B4Knowledge) : 
    (mu ∘ delta) a = a :=
  mu_delta_idempotent a

-- ── IGProtocol tier ──────────────────────────────────────────
def bit_tier : OuroboricityTier := TierFunctor.obj (B : Imscription)
#eval bit_tier  -- Expected: O_∞

end Imscribing
