-- IGProtocol scaffold: VINIT → AREV → FSPLIT → AFWD → CLINK → IMSCRIB → IFIX → CLINK → FSPLIT → EVALT → FFUSE → ENGAGR → IFIX → TANCH
-- Class: the whole construction is made checkable in Lean by the flat list-of-rationals power-basis engine that already reduces high powers under native_decide, never the nested-record tower that overflows the elaborator, with the four million overlap identities collapsed to their Galois and Weyl-Heisenberg orbit representatives exactly as the one hundred forty three d equals twelve overlaps collapsed to thirty one orbits sharing one displacement pair, this collapse being load-bearing because native_decide cannot face four million identities directly, so the decidable planks are the norm identity that the moduli sum to one in the real subfield, the per-orbit identity that each overlap times its explicit conjugation reduces in-ring to one over two thousand forty nine, and the magnitude identities that each cover square is the pinned product of two moduli, every plank generated by a script that re-verifies in Python fractions before emit and never hand-entered, with a genuine native_decide cost estimate reported so an intractable orbit count is surfaced rather than hidden
-- Fingerprint: sig=(7,3,2,2)
--   self_ref=False | frobenius_order=1
--   dialetheia_complete=False | period=14
-- Expected tier: O₁
-- FSPLIT/FFUSE pairs: [(8, 10)]

import Imscribing.IGMorphism
import Imscribing.IGFunctor

namespace Imscribing
open Primitives Frobenius IGProtocol
open Dimensionality Topology Relational Polarity Grammar
     Fidelity KineticChar Granularity Criticality Protection Stoichiometry Chirality

-- ── Token → IG field mapping ──────────────────────────────────────────────
--   [0] VINIT     dim    := 𐑼               𐑼 → 𐑗  | initial object — ground of distinction
--   [1] AREV      pol    := 𐑗               𐑼 → 𐑚  | reverse morphism — parity flip
--   [2] FSPLIT    gran   := 𐑚               𐑗 → 𐑾  | split δ — range decomposition
--   [3] AFWD      rel    := 𐑾               𐑚 → 𐑱  | forward morphism — bidirectional arrow
--   [4] CLINK     fid    := 𐑱               𐑾 → 𐑠  | composition — regime coherence
--   [5] IMSCRIB   gram   := 𐑠               𐑱 → 𐑭  | identity — self-imscription
--   [6] IFIX      prot   := 𐑭               𐑠 → 𐑱  | irreversible fixation — winding number
--   [7] CLINK     fid    := 𐑱               𐑭 → 𐑚  | composition — regime coherence
--   [8] FSPLIT    gran   := 𐑚               𐑚 → 𐑚  | split δ — range decomposition
--   [9] EVALT     crit   := ⊙               𐑚 → 𐑙  | evaluate-true — criticality gate open
--   [10] FFUSE     stoi   := 𐑙               𐑙 → 𐑳  | fuse μ — assembly mode
--   [11] ENGAGR    stoi   := 𐑳               𐑙 → 𐑭  | engage paradox — B-state, both arms
--   [12] IFIX      prot   := 𐑭               𐑳 → 𐑡  | irreversible fixation — winding number
--   [13] TANCH     top    := 𐑡               𐑭 → 𐑼  | terminal object — connectivity boundary

-- ── Stage Imscriptions (per-node cumulative) ────────────────
private def the_whole_construction_is_made_3a35c3_s0 : Imscription :=
  { dim := array, top := judge, rel := ado, pol := church, fid := age, kin := yea, gran := bib, gram := vow, crit := woe, chir := fee, stoi := hung, prot := awe }
private def the_whole_construction_is_made_3a35c3_s1 : Imscription :=
  { dim := array, top := judge, rel := ado, pol := church, fid := age, kin := yea, gran := bib, gram := vow, crit := woe, chir := fee, stoi := hung, prot := awe }
private def the_whole_construction_is_made_3a35c3_s2 : Imscription :=
  { dim := array, top := judge, rel := ado, pol := church, fid := age, kin := yea, gran := thigh, gram := vow, crit := woe, chir := fee, stoi := hung, prot := awe }
private def the_whole_construction_is_made_3a35c3_s3 : Imscription :=
  { dim := array, top := judge, rel := ian, pol := church, fid := age, kin := yea, gran := thigh, gram := vow, crit := woe, chir := fee, stoi := hung, prot := awe }
private def the_whole_construction_is_made_3a35c3_s4 : Imscription :=
  { dim := array, top := judge, rel := ian, pol := church, fid := age, kin := yea, gran := thigh, gram := vow, crit := woe, chir := fee, stoi := hung, prot := awe }
private def the_whole_construction_is_made_3a35c3_s5 : Imscription :=
  { dim := array, top := judge, rel := ian, pol := church, fid := age, kin := yea, gran := thigh, gram := measure, crit := woe, chir := fee, stoi := hung, prot := awe }
private def the_whole_construction_is_made_3a35c3_s6 : Imscription :=
  { dim := array, top := judge, rel := ian, pol := church, fid := age, kin := yea, gran := thigh, gram := measure, crit := woe, chir := fee, stoi := hung, prot := ah }
private def the_whole_construction_is_made_3a35c3_s7 : Imscription :=
  { dim := array, top := judge, rel := ian, pol := church, fid := age, kin := yea, gran := thigh, gram := measure, crit := woe, chir := fee, stoi := hung, prot := ah }
private def the_whole_construction_is_made_3a35c3_s8 : Imscription :=
  { dim := array, top := judge, rel := ian, pol := church, fid := age, kin := yea, gran := thigh, gram := measure, crit := woe, chir := fee, stoi := hung, prot := ah }
private def the_whole_construction_is_made_3a35c3_s9 : Imscription :=
  { dim := array, top := judge, rel := ian, pol := church, fid := age, kin := yea, gran := thigh, gram := measure, crit := monad, chir := fee, stoi := hung, prot := ah }
private def the_whole_construction_is_made_3a35c3_s10 : Imscription :=
  { dim := array, top := judge, rel := ian, pol := church, fid := age, kin := yea, gran := thigh, gram := measure, crit := monad, chir := fee, stoi := hung, prot := ah }
private def the_whole_construction_is_made_3a35c3_s11 : Imscription :=
  { dim := array, top := judge, rel := ian, pol := church, fid := age, kin := yea, gran := thigh, gram := measure, crit := monad, chir := fee, stoi := up, prot := ah }
private def the_whole_construction_is_made_3a35c3_s12 : Imscription :=
  { dim := array, top := judge, rel := ian, pol := church, fid := age, kin := yea, gran := thigh, gram := measure, crit := monad, chir := fee, stoi := up, prot := ah }
private def the_whole_construction_is_made_3a35c3_s13 : Imscription :=
  { dim := array, top := judge, rel := ian, pol := church, fid := age, kin := yea, gran := thigh, gram := measure, crit := monad, chir := fee, stoi := up, prot := ah }

-- ── Label Imscriptions (per-node delta) ─────────────────────
private def the_whole_construction_is_made_3a35c3_l0 : Imscription :=
  { dim := array, top := judge, rel := ado, pol := church, fid := age, kin := yea, gran := bib, gram := vow, crit := woe, chir := fee, stoi := hung, prot := awe }
private def the_whole_construction_is_made_3a35c3_l1 : Imscription :=
  { dim := dead, top := judge, rel := ado, pol := church, fid := age, kin := yea, gran := bib, gram := vow, crit := woe, chir := fee, stoi := hung, prot := awe }
private def the_whole_construction_is_made_3a35c3_l2 : Imscription :=
  { dim := dead, top := judge, rel := ado, pol := church, fid := age, kin := yea, gran := thigh, gram := vow, crit := woe, chir := fee, stoi := hung, prot := awe }
private def the_whole_construction_is_made_3a35c3_l3 : Imscription :=
  { dim := dead, top := judge, rel := ian, pol := church, fid := age, kin := yea, gran := bib, gram := vow, crit := woe, chir := fee, stoi := hung, prot := awe }
private def the_whole_construction_is_made_3a35c3_l4 : Imscription :=
  { dim := dead, top := judge, rel := ado, pol := church, fid := age, kin := yea, gran := bib, gram := vow, crit := woe, chir := fee, stoi := hung, prot := awe }
private def the_whole_construction_is_made_3a35c3_l5 : Imscription :=
  { dim := dead, top := judge, rel := ado, pol := church, fid := age, kin := yea, gran := bib, gram := measure, crit := woe, chir := fee, stoi := hung, prot := awe }
private def the_whole_construction_is_made_3a35c3_l6 : Imscription :=
  { dim := dead, top := judge, rel := ado, pol := church, fid := age, kin := yea, gran := bib, gram := vow, crit := woe, chir := fee, stoi := hung, prot := ah }
private def the_whole_construction_is_made_3a35c3_l7 : Imscription :=
  { dim := dead, top := judge, rel := ado, pol := church, fid := age, kin := yea, gran := bib, gram := vow, crit := woe, chir := fee, stoi := hung, prot := awe }
private def the_whole_construction_is_made_3a35c3_l8 : Imscription :=
  { dim := dead, top := judge, rel := ado, pol := church, fid := age, kin := yea, gran := thigh, gram := vow, crit := woe, chir := fee, stoi := hung, prot := awe }
private def the_whole_construction_is_made_3a35c3_l9 : Imscription :=
  { dim := dead, top := judge, rel := ado, pol := church, fid := age, kin := yea, gran := bib, gram := vow, crit := monad, chir := fee, stoi := hung, prot := awe }
private def the_whole_construction_is_made_3a35c3_l10 : Imscription :=
  { dim := dead, top := judge, rel := ado, pol := church, fid := age, kin := yea, gran := bib, gram := vow, crit := woe, chir := fee, stoi := hung, prot := awe }
private def the_whole_construction_is_made_3a35c3_l11 : Imscription :=
  { dim := dead, top := judge, rel := ado, pol := church, fid := age, kin := yea, gran := bib, gram := vow, crit := woe, chir := fee, stoi := up, prot := awe }
private def the_whole_construction_is_made_3a35c3_l12 : Imscription :=
  { dim := dead, top := judge, rel := ado, pol := church, fid := age, kin := yea, gran := bib, gram := vow, crit := woe, chir := fee, stoi := hung, prot := ah }
private def the_whole_construction_is_made_3a35c3_l13 : Imscription :=
  { dim := dead, top := judge, rel := ado, pol := church, fid := age, kin := yea, gran := bib, gram := vow, crit := woe, chir := fee, stoi := hung, prot := awe }

-- ── Main IGProtocol term ────────────────────────────────────
noncomputable def the_whole_construction_is_made_3a35c3_protocol : IGProtocol the_whole_construction_is_made_3a35c3_s0 the_whole_construction_is_made_3a35c3_s13 :=
  .withGram Grammar.measure <|
  -- Dual-Link self-pairing: .prod arms fuse via tensorProduct the_whole_construction_is_made_3a35c3_s10 the_whole_construction_is_made_3a35c3_s10 = the_whole_construction_is_made_3a35c3_s10 (idempotent)
  (.seq (.arrow the_whole_construction_is_made_3a35c3_l0 the_whole_construction_is_made_3a35c3_s0 the_whole_construction_is_made_3a35c3_s1) (.seq (.arrow the_whole_construction_is_made_3a35c3_l1 the_whole_construction_is_made_3a35c3_s1 the_whole_construction_is_made_3a35c3_s2) (.seq (.arrow the_whole_construction_is_made_3a35c3_l2 the_whole_construction_is_made_3a35c3_s2 the_whole_construction_is_made_3a35c3_s3) (.seq (.arrow the_whole_construction_is_made_3a35c3_l3 the_whole_construction_is_made_3a35c3_s3 the_whole_construction_is_made_3a35c3_s4) (.seq (.arrow the_whole_construction_is_made_3a35c3_l4 the_whole_construction_is_made_3a35c3_s4 the_whole_construction_is_made_3a35c3_s5) (.seq (.arrow the_whole_construction_is_made_3a35c3_l5 the_whole_construction_is_made_3a35c3_s5 the_whole_construction_is_made_3a35c3_s6) (.seq (.arrow the_whole_construction_is_made_3a35c3_l6 the_whole_construction_is_made_3a35c3_s6 the_whole_construction_is_made_3a35c3_s7) (.seq (.arrow the_whole_construction_is_made_3a35c3_l7 the_whole_construction_is_made_3a35c3_s7 the_whole_construction_is_made_3a35c3_s8) (.seq (.prod (.arrow the_whole_construction_is_made_3a35c3_l8 the_whole_construction_is_made_3a35c3_s8 the_whole_construction_is_made_3a35c3_s10) (.arrow the_whole_construction_is_made_3a35c3_l8 the_whole_construction_is_made_3a35c3_s8 the_whole_construction_is_made_3a35c3_s10)) (.seq (.arrow the_whole_construction_is_made_3a35c3_l10 the_whole_construction_is_made_3a35c3_s10 the_whole_construction_is_made_3a35c3_s10) (.seq (.arrow the_whole_construction_is_made_3a35c3_l10 the_whole_construction_is_made_3a35c3_s10 the_whole_construction_is_made_3a35c3_s11) (.seq (.arrow the_whole_construction_is_made_3a35c3_l11 the_whole_construction_is_made_3a35c3_s11 the_whole_construction_is_made_3a35c3_s12) (.arrow the_whole_construction_is_made_3a35c3_l12 the_whole_construction_is_made_3a35c3_s12 the_whole_construction_is_made_3a35c3_s13)))))))))))))

-- ── Evaluation arm sub-defs ───────────────────────────────────

-- truth arm
noncomputable def the_whole_construction_is_made_3a35c3_true_arm : IGProtocol the_whole_construction_is_made_3a35c3_s0 the_whole_construction_is_made_3a35c3_s13 :=
  (the_whole_construction_is_made_3a35c3_protocol).restrictToEVALT

-- ── Verification theorems ─────────────────────────────────────

-- Tier: apply the Grammar to the object (self-application). assess_tier verdict on the imscribed tuple: .O₁.
def the_whole_construction_is_made_3a35c3_tier : OuroboricityTier := TierFunctor.obj the_whole_construction_is_made_3a35c3_s0
#eval the_whole_construction_is_made_3a35c3_tier  -- the Grammar's own verdict on its tier

-- Frobenius (split → fuse): μ∘δ = id on the ground imscription
theorem the_whole_construction_is_made_3a35c3_frobenius :
    igFrobeniusAlg.mul the_whole_construction_is_made_3a35c3_s0 the_whole_construction_is_made_3a35c3_s0 = the_whole_construction_is_made_3a35c3_s0 :=
  igFrobAlg_self_fusion the_whole_construction_is_made_3a35c3_s0
