#!/usr/bin/env python3
"""I Ching Hexagram Divination: 64 hexagrams as divinatory system. FSPLIT is the yarrow stalk or coin toss splitting the moment into moving and static lines (yin/yang, old/new). Each hexagram with its moving lines (old yin becoming young yang, old yang becoming young yin) is the FSPLIT output. FFUSE reconstitutes the moment of consultation by reading the hexagram and its changing lines back into a unified oracle. The King Wen sequence provides the natural order. | Domain: divinatory | Frobenius: PASS
FSPLIT: The yarrow stalk or coin toss splitting the moment into moving and static lines | FFUSE: The reading of the hexagram and its changing lines back into a unified oracle
Auto-generated by ob3ect/auto.py — Author: Lando⊗⊙perator"""
import os, sys, json, pathlib
class IChingHexagramDivination64HexagramsAsDivinaOb3ect:
    def __init__(self):
        self.name="I Ching Hexagram Divination: 64 hexagrams as divinatory system. FSPLIT is the yarrow stalk or coin toss splitting the moment into moving and static lines (yin/yang, old/new). Each hexagram with its moving lines (old yin becoming young yang, old yang becoming young yin) is the FSPLIT output. FFUSE reconstitutes the moment of consultation by reading the hexagram and its changing lines back into a unified oracle. The King Wen sequence provides the natural order."; self.domain="divinatory"
        self.source=pathlib.Path(__file__).read_text()
        self.opcodes={        "VINIT": {"element":"The undifferentiated moment before consultation","justification":"Void/uninitialized state before any hexagram is cast."},
        "TANCH": {"element":"The King Wen sequence as the closed set of 64 hexagrams","justification":"Terminal anchor that bounds the entire divinatory system."},
        "AFWD": {"element":"The transformation from a static line to a moving line (e.g., young yin \u2192 old yin)","justification":"Forward morphism toward change and transformation."},
        "AREV": {"element":"The transformation from a moving line back to a static line (e.g., old yin \u2192 young yang)","justification":"Reverse/descent morphism returning to stability."},
        "CLINK": {"element":"The sequential reading of hexagram lines from bottom to top","justification":"Composition of line judgments into a unified oracle."},
        "ISCRIB": {"element":"The hexagram itself as a self-referential symbol","justification":"Each hexagram is a complete identity, recognized as itself."},
        "FSPLIT": {"element":"The yarrow stalk or coin toss splitting the moment into moving and static lines","justification":"Branches the consultation into six lines, each either static (yin/yang) or moving (old yin/yang)."},
        "FFUSE": {"element":"The reading of the hexagram and its changing lines back into a unified oracle","justification":"Reconstitutes the original moment of consultation by interpreting the hexagram and its transformations."},
        "EVALT": {"element":"A favorable oracle (e.g., hexagram 1: The Creative, with all lines auspicious)","justification":"Affirmative/true branch of divination."},
        "EVALF": {"element":"An unfavorable oracle (e.g., hexagram 47: Oppression, with all lines difficult)","justification":"Negative/false branch of divination."},
        "ENGAGR": {"element":"A hexagram with both auspicious and inauspicious lines, e.g., hexagram 63: After Completion","justification":"Paradox: both success and danger simultaneously."},
        "IFIX": {"element":"The recorded hexagram and its moving lines in a divination journal","justification":"Permanent irreversible record of the consultation."},}
        self.fsplit="The yarrow stalk or coin toss splitting the moment into moving and static lines"; self.ffuse="The reading of the hexagram and its changing lines back into a unified oracle"
        self.fsplit_input="The undifferentiated moment of consultation"; self.fsplit_outputs=["Six static lines (yin/yang)", "Six moving lines (old yin/yang)"]
        self.fuse_result="The unified oracle that interprets the moment of consultation"; self.frobenius_verdict="PASS"
        self.registers={"00":"00 \u2014 The moment before any hexagram is cast, pure potential.","01":"01 \u2014 A hexagram with all lines favorable, e.g., The Creative.","10":"10 \u2014 A hexagram with all lines unfavorable, e.g., Oppression.","11":"11 \u2014 A hexagram with mixed lines, e.g., After Completion."}
        self.bootstrap=[        {"step_num":1,"opcode":"IMSCRIB","domain_action":"Step 1 ISCRIB: The diviner recognizes the self as the one consulting the oracle."},
        {"step_num":2,"opcode":"AREV","domain_action":"Step 2 AREV:   The diviner descends into the moment, letting go of preconceptions."},
        {"step_num":3,"opcode":"FSPLIT","domain_action":"Step 3 FSPLIT: The diviner casts the yarrow stalks or coins, splitting the moment into six lines."},
        {"step_num":4,"opcode":"AFWD","domain_action":"Step 4 AFWD:   The diviner ascends by reading the hexagram from bottom to top."},
        {"step_num":5,"opcode":"FFUSE","domain_action":"Step 5 FFUSE:  The diviner fuses the hexagram and its moving lines into a unified oracle."},
        {"step_num":6,"opcode":"CLINK","domain_action":"Step 6 CLINK:  The diviner composes the line judgments into a coherent narrative."},
        {"step_num":7,"opcode":"IFIX","domain_action":"Step 7 IFIX:   The diviner records the hexagram and its interpretation permanently."},
        {"step_num":8,"opcode":"IMSCRIB","domain_action":"Step 8 ISCRIB: The diviner recognizes the self as having received the oracle, closing the cycle."},]
        self.exos={"compiler":"The diviner's mind that translates the question into the casting process.","ipc":"The symbolic language of hexagrams and line judgments that communicates between the moment and the oracle.","memory":"The recorded hexagram and its interpretation in the divination journal.","scheduler":"The natural timing of the consultation (e.g., when the question arises).","alfs":"The I Ching (Book of Changes) as the canonical reference."}
        self.entropy={"cost":"The mental energy and time spent in casting and interpreting.","pre":"The undifferentiated moment of uncertainty before consultation.","post":"The resolved moment with a recorded oracle.","verdict":"\u0394S \u2248 0 \u2014 The system cycles between uncertainty and resolution without net entropy increase."}
        self.tokens=["I Ching", "hexagram", "oracle"]; self.boundary="The 64 hexagrams of the King Wen sequence, which contains all possible configurations."
    def vf(self):
        if self.frobenius_verdict!="PASS":print(f"Frobenius FAIL");return False
        print(f"FSPLIT: {self.fsplit} -> {self.fsplit_outputs}");print(f"FFUSE: {self.fsplit_outputs} -> {self.fuse_result}");print(f"Frobenius: PASS");return True
    def vb(self):
        if len(self.bootstrap)!=8:print("Bootstrap FAIL: need 8");return False
        if self.bootstrap[0]["opcode"]!="IMSCRIB" or self.bootstrap[7]["opcode"]!="IMSCRIB":print("Bootstrap FAIL: IMSCRIB");return False
        print("Bootstrap: 8 steps OK");return True
    def vr(self):
        for s in ["00","01","10","11"]:
            if not self.registers.get(s,""):print(f"Reg FAIL: {s}");return False
        print("Registers: OK");return True
    def vo(self):
        exp={"VINIT","TANCH","AFWD","AREV","CLINK","IMSCRIB","FSPLIT","FFUSE","EVALT","EVALF","ENGAGR","IFIX"}
        m=exp-set(self.opcodes.keys())
        if m:print(f"Opcodes FAIL: missing {m}");return False
        for o in exp:
            if not self.opcodes[o].get("element",""):print(f"Opcode {o} empty");return False
        print("Opcodes: 12/12 OK");return True
    def verify(self):
        print(f"=== {self.name} ===\nDomain: {self.domain}\nTokens: {', '.join(self.tokens)}\nBoundary: {self.boundary}\n")
        c=[("Opcodes",self.vo()),("Registers",self.vr()),("Frobenius",self.vf()),("Bootstrap",self.vb())]
        a=all(p for _,p in c);print(f"\nClosure: {a}");return a
    def report(self):
        l=[f"=== {self.name} ===",f"Frobenius: {self.frobenius_verdict}",f"FSPLIT: {self.fsplit}",f"FFUSE: {self.ffuse}","\nOpcodes:"]
        for o,e in sorted(self.opcodes.items()):l.append(f"  {o:>8} -> {e['element']}")
        l.append("\nRegisters:")
        for s,d in self.registers.items():l.append(f"  {s}: {d}")
        l.append("\nBootstrap:")
        for s in self.bootstrap:l.append(f"  Step {s['step_num']}: {s['opcode']} - {s['domain_action']}")
        return "\n".join(l)
if __name__=="__main__":
    o=IChingHexagramDivination64HexagramsAsDivinaOb3ect(); ok=o.verify(); print(); print(o.report()); sys.exit(0 if ok else 1)
