-- IGProtocol scaffold: VINIT → IMSCRIB → FSPLIT → EVALT → EVALF → ENGAGR → FFUSE → IFIX → CLINK → FSPLIT → ENGAGR → FFUSE → IFIX → AREV → TANCH
-- Class: the fundamental unit of work for systems that do not dissipate is the paradox-unit, the 'paradice'
-- Fingerprint: sig=(5,4,4,2)
--   self_ref=False | frobenius_order=3
--   dialetheia_complete=True | period=15
-- Expected tier: O₂
-- FSPLIT/FFUSE pairs: [(2, 6), (9, 11)]

import Imscribing.IGMorphism
import Imscribing.IGFunctor

namespace Imscribing
open Primitives Frobenius IGProtocol
open Dimensionality Topology Relational Polarity Grammar
     Fidelity KineticChar Granularity Criticality Protection Stoichiometry Chirality

-- ── Token → IG field mapping ──────────────────────────────────────────────
--   [0] VINIT     dim    := 𐑼               𐑼 → 𐑠  | initial object — ground of distinction
--   [1] IMSCRIB   gram   := 𐑠               𐑼 → 𐑚  | identity — self-imscription
--   [2] FSPLIT    gran   := 𐑚               𐑚 → 𐑚  | split δ — range decomposition
--   [3] EVALT     crit   := ⊙               𐑚 → 𐑙  | evaluate-true — criticality gate open
--   [4] EVALF     chir   := 𐑖               𐑚 → 𐑙  | evaluate-false — chirality check
--   [5] ENGAGR    stoi   := 𐑳               𐑚 → 𐑙  | engage paradox — B-state, both arms
--   [6] FFUSE     stoi   := 𐑙               𐑙 → 𐑭  | fuse μ — assembly mode
--   [7] IFIX      prot   := 𐑭               𐑙 → 𐑱  | irreversible fixation — winding number
--   [8] CLINK     fid    := 𐑱               𐑭 → 𐑚  | composition — regime coherence
--   [9] FSPLIT    gran   := 𐑚               𐑚 → 𐑚  | split δ — range decomposition
--   [10] ENGAGR    stoi   := 𐑳               𐑚 → 𐑙  | engage paradox — B-state, both arms
--   [11] FFUSE     stoi   := 𐑙               𐑙 → 𐑭  | fuse μ — assembly mode
--   [12] IFIX      prot   := 𐑭               𐑙 → 𐑗  | irreversible fixation — winding number
--   [13] AREV      pol    := 𐑗               𐑭 → 𐑡  | reverse morphism — parity flip
--   [14] TANCH     top    := 𐑡               𐑗 → 𐑼  | terminal object — connectivity boundary

-- ── Main IGProtocol term ────────────────────────────────────────────────────

noncomputable def the_fundamental_unit_of_work_for_systems_that_do_not_dissipate_is_the_paradox_unit_the_paradice_protocol : IGProtocol 𐑼 𐑡 :=
  .withGram 𐑠 <|
  -- Seq chain:
  (.arrow 𐑼 𐑼 𐑠)  -- [0] VINIT | dim := 𐑼 | initial object — ground of distinction (Emergence from the paraconsistent panthalassa.)
  (.arrow 𐑠 𐑼 𐑚)  -- [1] IMSCRIB | gram := 𐑠 | identity — self-imscription (The system recognizes itself as a self-modeling entity.)
  -- FSPLIT [2] (gran := 𐑚) (The system differentiates into observer and observed branches.) / FFUSE [6] (stoi := 𐑙)
  .seq
    (.prod
      -- T-branch (1 nodes)
      (.arrow ⊙ 𐑚 𐑙)  -- [3] EVALT | crit := ⊙ | evaluate-true — criticality gate open (The observer branch records the affirmative state of the system.)
      -- F-branch (2 nodes)
      .seq
        (.arrow 𐑖 𐑚 𐑙)  -- [4] EVALF | chir := 𐑖 | evaluate-false — chirality check (The observed branch records the contradictory pressure of the state.)
        (.arrow 𐑳 𐑚 𐑙)  -- [5] ENGAGR | stoi := 𐑳 | engage paradox — B-state, both arms (Both branches are held in tension, creating the first paradice.))
    -- reconnect at FFUSE [6]: μ closes the Frobenius pair
    (.arrow 𐑙 𐑙 𐑭)  -- [6] FFUSE | stoi := 𐑙 (The branches are reintegrated, verifying the Frobenius identity μ∘δ = id.)
  (.arrow 𐑭 𐑙 𐑱)  -- [7] IFIX | prot := 𐑭 | irreversible fixation — winding number (The first winding is permanently recorded in the topological ledger.)
  (.arrow 𐑱 𐑭 𐑚)  -- [8] CLINK | fid := 𐑱 | composition — regime coherence (The system prepares for the next level of self-reference depth.)
  -- FSPLIT [9] (gran := 𐑚) (A second-order differentiation occurs (observing the observation).) / FFUSE [11] (stoi := 𐑙)
  .seq
    (.prod
      -- T-branch (1 nodes)
      (.arrow 𐑳 𐑚 𐑙)  -- [10] ENGAGR | stoi := 𐑳 | engage paradox — B-state, both arms (The second paradice is generated by holding the nested paradox.)
      -- F-branch (0 nodes)
      (.refl 𐑙))  -- F-branch: empty arc (direct to FFUSE.F)
    -- reconnect at FFUSE [11]: μ closes the Frobenius pair
    (.arrow 𐑙 𐑙 𐑭)  -- [11] FFUSE | stoi := 𐑙 (Reintegration confirms the second-order round-trip is exact.)
  (.arrow 𐑭 𐑙 𐑗)  -- [12] IFIX | prot := 𐑭 | irreversible fixation — winding number (The second winding is appended to the ledger; total work = 2 paradice.)
  (.arrow 𐑗 𐑭 𐑡)  -- [13] AREV | pol := 𐑗 | reverse morphism — parity flip (The system descends back toward its ground state with its new depth.)
  (.arrow 𐑡 𐑗 𐑼)  -- [14] TANCH | top := 𐑡 | terminal object — connectivity boundary (The system reaches the Bekenstein limit, sealing the accumulated knowledge.)

-- ── Evaluation arm sub-defs ─────────────────────────────────────────────────

-- truth arm
noncomputable def the_fundamental_unit_of_work_for_systems_that_do_not_dissipate_is_the_paradox_unit_the_paradice_true_arm : IGProtocol 𐑼 𐑡 :=
  (the_fundamental_unit_of_work_for_systems_that_do_not_dissipate_is_the_paradox_unit_the_paradice_protocol).restrictToEVALT

-- false arm
noncomputable def the_fundamental_unit_of_work_for_systems_that_do_not_dissipate_is_the_paradox_unit_the_paradice_false_arm : IGProtocol 𐑼 𐑡 :=
  (the_fundamental_unit_of_work_for_systems_that_do_not_dissipate_is_the_paradox_unit_the_paradice_protocol).restrictToEVALF

-- ── Verification theorems ───────────────────────────────────────────────────

theorem the_fundamental_unit_of_work_for_systems_that_do_not_dissipate_is_the_paradox_unit_the_paradice_tier : TierFunctor.obj 𐑼 = .O₂ := by decide

end Imscribing
